$(document).ready(function() {
  var _that = this;
  /**
   * Describe this function...
   */
  function Container2__Container__tellMeWho3() {
    return new Promise(function(resolve, reject) {
      // Block#: zxerfG=}!9)IrbD~q`hy
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("Container2_Container_Label", 'Super Lib');
    });
  }
  /**
   * Describe this function...
   */
  function ChildLib__SuperLib__getLibName() {
    return 'Super Lib';
  }
  /**
   * Describe this function...
   */
  // Imported from Lib: SuperLib
  function ChildLib__getSuperLibName() {
    return ChildLib__SuperLib__getLibName();
  }
  /**
   * Describe this function...
   */
  function Container2__generateStructure() {
    return new Promise(function(resolve, reject) {
      // Imported from Lib: SuperLib
      // Block#: B;%tDlq`c+:~Mgv%6lTs
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("Container2_Label", (String(Container2__SuperLib__getLibName()) + String('-> Child Lib')));
    });
  }
  /**
   * Describe this function...
   */
  function ChildLib__getLibName2() {
    return 'Child Lib';
  }
  /**
   * Describe this function...
   */
  function Container2__generateStructure2() {
    return new Promise(function(resolve, reject) {
      // Imported from Lib: SuperLib
      // Block#: [h#@r8_yD:-|`Hsqu0^i
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("Container2_Label", (String(Container2__SuperLib__getLibName()) + String('-> Child Lib')));
    });
  }
  /**
   * Describe this function...
   */
  function Container2__Container__tellMeWho() {
    return new Promise(function(resolve, reject) {
      // Block#: WDbfj!v{R8?2?xxpcrE?
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("Container2_Container_Label", 'Super Lib');
    });
  }
  /**
   * Describe this function...
   */
  function Container2__Container__tellMeWho2() {
    return new Promise(function(resolve, reject) {
      // Block#: quMxrnKmewIvGd^7v3wN
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("Container2_Container_Label", 'Super Lib');
    });
  }
  /**
   * Describe this function...
   */
  function Container2__SuperLib__getLibName() {
    return 'Super Lib';
  }
  // Block#: 7@t^mF-|i2`Gf_zHm:AA
  function on_Button_click(e) {
    try {
      // Imported from Lib: ChildLib
      // Block#: *d%[{FV#47D^`2Ji(jm0
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("Label", (ChildLib__getSuperLibName()));
      e.stopPropagation();
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  $('[obj-name="Button"]').on('click', on_Button_click);
  // Block#: +XD_L16C6r7G~^W8zK2T
  function on_Container2_Button_click(e) {
    try {
      // Block#: h:dr}-dM2XE|sDG]x.,w
      Container2__generateStructure().then(response => {;
      });
      e.stopPropagation();
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  $('[obj-name="Container2_Button"]').on('click', on_Container2_Button_click);
  // Block#: ]6k-pgIl?UNcz/Y.L`DZ
  function on_Container2_Container_Button_click(e) {
    try {
      // Block#: q~ko9@jLm2:)G:0c6R_i
      Container2__Container__tellMeWho().then(response => {;
      });
      e.stopPropagation();
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  $('[obj-name="Container2_Container_Button"]').on('click', on_Container2_Container_Button_click);
  $('[obj-name="MainScreen"]').show();
});
// Generated by snapp
// 183246-354586-454177-266452
